{% set name = "pynecone" %}
{% set version = "0.1.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynecone-{{ version }}.tar.gz
  sha256: 75dde34884f32f13f48965244449d670bbc6358700f5fab858d2d7399d979eea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.7,<4.0
  run:
    - cloudpickle >=2.2.1,<3.0.0
    - fastapi >=0.92.0,<0.93.0
    - gunicorn >=20.1.0,<21.0.0
    - httpx >=0.23.1,<0.24.0
    - jinja2 >=3.1.2,<4.0.0
    - nodejs >=16.8.0
    - plotly >=5.13.0,<6.0.0
    - psutil >=5.9.4,<6.0.0
    - pydantic ==1.10.2
    - python >=3.7,<4.0
    - python-multipart >=0.0.5,<0.0.6
    - python-socketio >=5.7.0,<6.0.0
    - redis-py >=4.3.5,<5.0.0
    - rich >=13.0.0,<14.0.0
    - sqlmodel >=0.0.8,<0.0.9
    - typer ==0.4.2
    - unzip
    - uvicorn >=0.20.0,<0.21.0
    - watchdog >=2.3.1,<3.0.0
    - websockets >=10.4,<11.0

test:
  imports:
    - pynecone
  commands:
    - pip list
    - pip check
    - mkdir test_app;cd test_app;pc init;ls
  requires:
    - pip

about:
  home: https://pynecone.io
  summary: Web apps in pure Python.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Alek99
    - goanpeca
